server:
  port: 8082

spring:
  application:
    name: clinic_profile
  datasource:
    url: jdbc:mysql://localhost:3306/clinic_profile?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
