server:
  port: 8084

spring:
  application:
    name: clinic_medical_record

  datasource:
    url: jdbc:mysql://localhost:3306/clinic_medical_record?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

services:
  identity-url: http://localhost:8081
  appointment-url: http://localhost:8083
  notification-url: http://localhost:8086
